### PR TITLE
Added mcmaukissa

### PR DESCRIPTION
**Pull request by Snattuw**
I added the mcmaukissa server

### CODE REVIEW

**Review by Anakinnnnn — CHANGES_REQUESTED** [review]
Do you have a better logo than that?

**Comment by Snattuw** [comment]
What do I need to improve on the logo? It might look a bit unsharp because I had to upscale it to 512px

**Comment by Snattuw** [comment]
I can upload a much sharper image

**Comment by Snattuw** [comment]
logo

**Pull request closed without merging**
