### PR TITLE
PvP Heaven

### PR DESCRIPTION
**Pull request by Spoony1337**
Fixed PvP Heaven Pull Request

### CODE REVIEW

**Comment by ziuee** [comment]
the skid spoony on it again making shitty server with his leaked src’s!!!

**Comment by GrowlyX** [comment]
@ziuee, please stop.

**Review by GrowlyX — APPROVED** [review]

**Comment by PrestigePvP** [comment]
Denied, for inappropriate community behavior. Please be more respectful to community members, if this happens again you will not be allowed to post or comment on this repo.

**Comment by ziuee** [comment]
He first attacked me on my PR so I was simply just getting revenge. But it’s weird how he and his friends was allowed to but not me.

**Comment by Spoony1337** [comment]
> He first attacked me on my PR so I was simply just getting revenge. But it’s weird how he and his friends was allowed to but not me.

If you cannot see my PR was denied aswell, you are legit commenting on it.

**Pull request closed without merging**
