### PR TITLE
Added bridge.rip

### PR DESCRIPTION
**Pull request by AdamAtomus**

### CODE REVIEW

**Review by wi — CHANGES_REQUESTED** [review]
both your background and logo are clear copyright from mine HQ. You will have to fix this before we can merge this.

**Comment by Vaxp** [comment]
They're literally copying my old server which I used to copy minehq LOOOOOL I was the one who changed the logo text (well a friend of mine did but it was for me)

**Comment by Vaxp** [comment]
Just don't merge it lmfao it's a minehq clone

**Comment by AdamAtomus** [comment]
> Just don't merge it lmfao it's a minehq clone

It’s not a mineHQ clone, unlike your server, I also meant to use the new logo we made, stop coming to my pull requests to complain, you are being immature, especially for your age.

**Comment by gtxg16** [comment]
Adam is right. You need to stop being immature. Grow up. You are being immature.

**Comment by AdamAtomus** [comment]
> both your background and logo are clear copyright from mine HQ. You will have to fix this before we can merge this.

I’ll fix the logo once I’m off work, sorry about the logo :)

**Comment by egirldevs** [comment]
LOOOOOL bro topu calm down 💀 dont you have potpvp anyways

**Comment by ceocharley** [comment]
topu malding 💀😭

**Comment by uzizach** [comment]
topu how are u still mad, you call us weird, yet log onto our server atleast once a day, you say your not mad but ur clearly pissed off we used ur domain THAT YOU NO LONGER PAY FOR, grow up, your 21 years old

**Comment by AdamAtomus** [comment]
@wi charley fixed the logo, sorry bout the comments :)

**Comment by gtxg16** [comment]
My dad owns GitHub he can get you banned

**Review by wi — APPROVED** [review]

**Pull request merged**
