### PR TITLE
Add SunPvP Network

### PR DESCRIPTION
**Pull request by ValoriomMX**

### CODE REVIEW

**Comment by ValoriomMX** [comment]
server-icon

**Review by GrowlyX — APPROVED** [review]

**Comment by GrowlyX** [comment]
_Heads up:_ The logo you commented will not be registered as you didn't add its png file to the logos directory.

**Comment by ValoriomMX** [comment]
> _Heads up:_ The logo you commented will not be registered as you didn't add its png file to the logos directory.

I can add the png to that directory

**Comment by GrowlyX** [comment]
> > _Heads up:_ The logo you commented will not be registered as you didn't add its png file to the logos directory.
> 
> I can add the png to that directory

Thanks!

**Review by GrowlyX — APPROVED** [review]

**Pull request merged**
