### PR TITLE
Fixed Sunrise City Server

### PR DESCRIPTION
**Pull request by skepiaa**
### General:
* [x] The pull request title is descriptive. *(ex. `Added Lunar Network`, not `Updated servers.json`)*
* [x] The pull request does not contain any unrelated commits.  *(ex. commits from previous pull requests)*

### Mapping Additions or Updates:
* [x] No changes were made to the file's formatting.
* [x] There are no syntax errors.
* [x] There is no pre-existing mapping matching my id.
* [x] My field values match your requirements.
* You can view our patterns here: [servers.schema.json](https://github.com/LunarClient/ServerMappings/blob/master/servers.schema.json), or take a look below and complete the field checklist:
  - [x] `id`: a lowercase string *(ex. `myserver`)*
  - [x] `name`: a string *(ex. `MyServerPvP`)*
  - [x] `addresses`: an array with lowercase strings *(ex. `["my.server", "your-server.com"]`)*
    - You do not need to specify subdomains, Lunar Client services automatically detect them.
  - [x] `primaryAddress`: an address *(ex. `my.server`)*
  - [x] `minecraftVersions`: an array with Minecraft versions as strings *(ex. `["1.18", "1.19"]`)*
  - [x] `primaryMinecraftVersion`: a Minecraft version as a string *(ex. `1.18`)*

### Logo Additions or Updates:
* [x] My image is a `png` file.
* [x] I uploaded my image to the `logos` directory.
* [ ] My image has a transparent background and is square (1:1 aspect ratio).
* [x] My image is `512` pixels in width and height.
* [x] My image's file name matches its mapping id.

The server IP requires the play. in order to connect, else it would say Unknown Host.

### CODE REVIEW

**Comment by JustSkeppYT** [comment]
The server IP requires the play. in order to connect, else it would say Unknown Host.

**Comment by itsJordan** [comment]
> The server IP requires the play. in order to connect, else it would say Unknown Host.

I've had a look at the merged PR #467 and the 'play' subdomain is already included in the relevant section "primaryAddress".

The "primaryAddress" field is used when actually connecting a player onto a server.

The domains listed within the "addresses" array are used for matching all possible subdomains onto the same domain. 
For example: "play.sunrisecity.uk" and "mc.sunrisecity.uk" would both match to "sunrisecity", even if no players have connected using the "mc" subdomain.

If I have misunderstood something, or if you have any further questions - feel free to leave another comment. 
If not, I'll close this in a couple days.

**Comment by JustSkeppYT** [comment]
That's weird, when I attempted to join my friend with Sunrise City Server, they got an error of "Unknown Host" when connecting, although the IP **play.sunrisecity.uk** works perfectly when trying, although does not with lunar client join server button.

**Comment by ThatKawaiiSam** [comment]
Hi @JustSkeppYT,

We have moved to a new format for submitting servers and as such I will close this PR. Please submit a new PR in the new format.

**Pull request closed without merging**
