### PR TITLE
Added Kazer Network

### PR DESCRIPTION
**Pull request by RareMan666**
### General:
* [x] The pull request title is descriptive. *(ex. `Added Lunar Network`, not `Updated servers.json`)*
* [x] The pull request does not contain any unrelated commits.  *(ex. commits from previous pull requests)*

### Mapping Additions or Updates:
* [x] No changes were made to the file's formatting.
* [x] There are no syntax errors.
* [x] There is no pre-existing mapping matching my id.
* [x] My field values match your requirements.
* You can view our patterns here: [servers.schema.json](https://github.com/LunarClient/ServerMappings/blob/master/servers.schema.json), or take a look below and complete the field checklist:
  - [x] `id`: a lowercase string *(ex. `myserver`)*
  - [x] `name`: a string *(ex. `MyServerPvP`)*
  - [x] `addresses`: an array with lowercase strings *(ex. `["my.server", "your-server.com"]`)*
    - You do not need to specify subdomains, Lunar Client services automatically detect them.
  - [x] `primaryAddress`: an address *(ex. `my.server`)*
  - [x] `minecraftVersions`: an array with Minecraft versions as strings *(ex. `["1.18", "1.19"]`)*
  - [x] `primaryMinecraftVersion`: a Minecraft version as a string *(ex. `1.18`)*

### Logo Additions or Updates:
* [ ] My image is a `png` file.
* [x] I uploaded my image to the `logos` directory.
* [ ] My image has a transparent background and is square (1:1 aspect ratio).
* [x] My image is `512` pixels in width and height.
* [x] My image's file name matches its mapping id.

### CODE REVIEW

**Review by itsJordan — CHANGES_REQUESTED** [review]
Could you please include a higher resolution version of this logo? (still 512x512)

If the logo is supposed to be pixilated, could you please up-scale this image using a more appropriate method to avoid the blurry appearance.

**Comment by Fragments-Blade** [comment]
Ok, i upload it, please check it again! Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LunarClient/ServerMappings"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月31日(星期天) 晚上10:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LunarClient/ServerMappings] Added Kazer Network (PR #433)





 
@itsJordan requested changes on this pull request.
 
Could you please include a higher resolution version of this logo? (still 512x512)
 
If the logo is supposed to be pixilated, could you please up-scale this image using a more appropriate method to avoid the blurry appearance.

**Review by GrowlyX — DISMISSED** [review]
Your logo does not match our sizing requirements of 512x512 pixels.

**Comment by Fragments-Blade** [comment]
oh, i forgot it, sorry! can you check it again?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LunarClient/ServerMappings"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月31日(星期天) 晚上10:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LunarClient/ServerMappings] Added Kazer Network (PR #433)





 
@GrowlyX requested changes on this pull request.
 
Your logo does not match our sizing requirements of 512x512 pixels.

**Comment by Fragments-Blade** [comment]
i just upload failed, now i succssfully upload it, can you check it again?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LunarClient/ServerMappings"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月31日(星期天) 晚上10:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LunarClient/ServerMappings] Added Kazer Network (PR #433)





 
@GrowlyX requested changes on this pull request.
 
Your logo does not match our sizing requirements of 512x512 pixels.

**Comment by Fragments-Blade** [comment]
i upload this, can you check it again?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LunarClient/ServerMappings"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月31日(星期天) 晚上10:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LunarClient/ServerMappings] Added Kazer Network (PR #433)





 
@itsJordan requested changes on this pull request.
 
Could you please include a higher resolution version of this logo? (still 512x512)
 
If the logo is supposed to be pixilated, could you please up-scale this image using a more appropriate method to avoid the blurry appearance.

**Comment by Fragments-Blade** [comment]
hey, can you check it again? Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LunarClient/ServerMappings"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月31日(星期天) 晚上10:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LunarClient/ServerMappings] Added Kazer Network (PR #433)





 
@GrowlyX requested changes on this pull request.
 
Your logo does not match our sizing requirements of 512x512 pixels.

**Comment by Fragments-Blade** [comment]
hello? can you check it again?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LunarClient/ServerMappings"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月31日(星期天) 晚上10:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LunarClient/ServerMappings] Added Kazer Network (PR #433)





 
@itsJordan requested changes on this pull request.
 
Could you please include a higher resolution version of this logo? (still 512x512)
 
If the logo is supposed to be pixilated, could you please up-scale this image using a more appropriate method to avoid the blurry appearance.

**Comment by itsJordan** [comment]
> hello? can you check it again?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "LunarClient/ServerMappings" ***@***.***&gt;; 发送时间:&nbsp;2022年7月31日(星期天) 晚上10:21 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [LunarClient/ServerMappings] Added Kazer Network (PR #433) @itsJordan requested changes on this pull request. Could you please include a higher resolution version of this logo? (still 512x512) If the logo is supposed to be pixilated, could you please up-scale this image using a more appropriate method to avoid the blurry appearance. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Logo is still not being detected as a valid PNG file - Could you please re-export your logo in the PNG file format and remove the background from the image.

**Review by itsJordan — APPROVED** [review]

**Pull request merged**
