### PR TITLE
Added Scala

### PR DESCRIPTION
**Pull request by GrowlyX**

### CODE REVIEW

**Comment by colinmcdonald22** [comment]
what in the world is that website

**Comment by GrowlyX** [comment]
> what in the world is that website

https://github.com/feross/TheAnnoyingSite.com

**Comment by ItzBunniYT** [comment]
> what in the world is that website

LOL its something I setup for growly to mess with someone LOL

**Comment by GrowlyX** [comment]
someone merge this, it doesn't let me merge my own pr

**Review by imconnorngl — APPROVED** [review]

**Comment by GrowlyX** [comment]
closing because this is broken

**Pull request closed without merging**
