### PR TITLE
Added PvP Heaven

### PR DESCRIPTION
**Pull request by Spoony1337**
Added my PvP Heaven Network

### CODE REVIEW

**Comment by Spoony1337** [comment]
Logo: 
image

**Comment by GrowlyX** [comment]
> Logo: image

You need to upload that image to the logos directory.

**Comment by ziuee** [comment]
Oh god it’s the skid himself! Spoony! Doesn’t know how to even upload a logo LOOOL

**Comment by ziuee** [comment]
Should stick to skidding instead spoony, look like this is too complicated for your brain to handle.

**Comment by Spoony1337** [comment]
oops mb

**Comment by Spoony1337** [comment]
I didn't even realize it needed a logo till I checked out other people's pull requests

**Comment by Spoony1337** [comment]
> Oh god it’s the skid himself! Spoony! Doesn’t know how to even upload a logo LOOOL

Didn't even realize it needed a logo till I check out other people's pull requests's go back to skidding yang

**Comment by GrowlyX** [comment]
Please stop using this as a place to fight.

**Pull request closed without merging**
