### PR TITLE
Added Kazer Network

### PR DESCRIPTION
**Pull request by RareMan666**
### General:
* [x] The pull request title is descriptive. *(ex. `Added Lunar Network`, not `Updated servers.json`)*
* [x] The pull request does not contain any unrelated commits.  *(ex. commits from previous pull requests)*

### Mapping Additions or Updates:
* [x] No changes were made to the file's formatting.
* [x] There are no syntax errors.
* [x] There is no pre-existing mapping matching my id.
* [x] My field values match your requirements.
* You can view our patterns here: [servers.schema.json](https://github.com/LunarClient/ServerMappings/blob/master/servers.schema.json), or take a look below and complete the field checklist:
  - [x] `id`: a lowercase string *(ex. `myserver`)*
  - [x] `name`: a string *(ex. `MyServerPvP`)*
  - [x] `addresses`: an array with lowercase strings *(ex. `["my.server", "your-server.com"]`)*
    - You do not need to specify subdomains, Lunar Client services automatically detect them.
  - [x] `primaryAddress`: an address *(ex. `my.server`)*
  - [x] `minecraftVersions`: an array with Minecraft versions as strings *(ex. `["1.18", "1.19"]`)*
  - [x] `primaryMinecraftVersion`: a Minecraft version as a string *(ex. `1.18`)*

### Logo Additions or Updates:
* [x] My image is a `png` file.
* [x] I uploaded my image to the `logos` directory.
* [x] My image has a transparent background and is square (1:1 aspect ratio).
* [x] My image is `512` pixels in width and height.
* [x] My image's file name matches its mapping id.

### CODE REVIEW

**Review by itsJordan — CHANGES_REQUESTED** [review]
Please include the following properties in your servers.json:

primaryAddress,
minecraftVersions,
primaryMinecraftVersion

Additional information can now be found in the README

**Comment by Fragments-Blade** [comment]
i added primary address, minecraft versions and primary minecraft version, can you check it again?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LunarClient/ServerMappings"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月31日(星期天) 晚上7:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LunarClient/ServerMappings] Added Kazer Network (PR #431)





 
@itsJordan requested changes on this pull request.
 
Please include the following properties in your servers.json:
 
primaryAddress,
 minecraftVersions,
 primaryMinecraftVersion
 
Additional information can now be found in the README

**Comment by itsJordan** [comment]
Replaced by #433

**Comment by Fragments-Blade** [comment]
hey jordan, i see you review it, but you are not add it to servers.json, so can you add it? Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LunarClient/ServerMappings"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月31日(星期天) 晚上9:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LunarClient/ServerMappings] Added Kazer Network (PR #431)





 
Closed #431.

**Pull request closed without merging**
