### PR TITLE
Add FadeMC

### PR DESCRIPTION
**Pull request by permitir**
logo: https://cdn.discordapp.com/attachments/954109251092115466/970402046765334548/fademcdragon.webp

### General:
* [ ] The pull request title is descriptive. *(ex. `Added Lunar Network`, not `Updated servers.json`)*
* [ ] The pull request does not contain any unrelated commits.  *(ex. commits from previous pull requests)*

### Mapping Additions or Updates:
* [ ] No changes were made to the file's formatting.
* [ ] There are no syntax errors.
* [ ] There is no pre-existing mapping matching my id.
* [ ] My field values match your requirements.
* You can view our patterns here: [servers.schema.json](https://github.com/LunarClient/ServerMappings/blob/master/servers.schema.json), or take a look below and complete the field checklist:
  - [ ] `id`: a lowercase string *(ex. `myserver`)*
  - [ ] `name`: a string *(ex. `MyServerPvP`)*
  - [ ] `addresses`: an array with lowercase strings *(ex. of address `my.server`)*
    - You do not need to specify sub-domains, Lunar Client services automatically detect them.

### Logo Additions or Updates:
* [ ] My image is a `png` file.
* [ ] I uploaded my image to the `logos` directory.
* [ ] My image has a transparent background and is square (1:1 aspect ratio).
* [ ] My image is `512` pixels in width and height.
* [ ] My image's file name matches its mapping id.

### CODE REVIEW

**Review by jacobk999 — CHANGES_REQUESTED** [review]
Add your logo to the logos directory. Don't upload it to this repository, upload it to your fork of the repo.

**Comment by ignCotx** [comment]
> 

I'm sorry but I don't really know how to do what you just told me, are you able to tell me a step by step? because when I go and try to do it I can't, I even tried looking on google.

**Review by GrowlyX — CHANGES_REQUESTED** [review]
You can add your logo by returning to your ServerMappings fork, navigating to the logos directory, and clicking the `Add File` button.

**Comment by ignCotx** [comment]
> You can add your logo by returning to your ServerMappings fork, navigating to the logos directory, and clicking the `Add File` button.

done, can you check if its correct?

**Comment by ignCotx** [comment]
> > You can add your logo by returning to your ServerMappings fork, navigating to the logos directory, and clicking the `Add File` button.
> 
> done, can you check if its correct?

this is where I uploaded it
https://github.com/LunarClient/ServerMappings/blob/8e51839eb003d1b1509b6660c7debb808177e3b1/logos/fademc.png

**Pull request closed without merging**
