### PR TITLE
Add EdenMine Network

### PR DESCRIPTION
**Pull request by overkidding**

### CODE REVIEW

**Comment by bernie-g** [comment]
Wouldn't it be better for this to have a display name that's not the IP?

**Comment by colinmcdonald22** [comment]
Additionally, you can supply just `edenmine.eu`, as this system looks as suffixes

**Comment by overkidding** [comment]
> Additionally, you can supply just `edenmine.eu`, as this system looks as suffixes

Thank you for your suggestion, done.

**Comment by overkidding** [comment]
> Wouldn't it be better for this to have a display name that's not the IP?

Thank you for your suggestion, changed to a display name.

**Pull request merged**
