### PR TITLE
Added Crystal Network

### PR DESCRIPTION
**Pull request by ziuee**
### General:
* [ ] The pull request title is descriptive. *(ex. `Added Lunar Network`, not `Updated servers.json`)*
* [ ] The pull request does not contain any unrelated commits.  *(ex. commits from previous pull requests)*

### Mapping Additions or Updates:
* [ ] No changes were made to the file's formatting.
* [ ] There are no syntax errors.
* [ ] There is no pre-existing mapping matching my id.
* [ ] My field values match your requirements.
* You can view our patterns here: [servers.schema.json](https://github.com/LunarClient/ServerMappings/blob/master/servers.schema.json), or take a look below and complete the field checklist:
  - [ ] `id`: a lowercase string *(ex. `myserver`)*
  - [ ] `name`: a string *(ex. `MyServerPvP`)*
  - [ ] `addresses`: an array with lowercase strings *(ex. of address `my.server`)*
    - You do not need to specify sub-domains, Lunar Client services automatically detect them.

### Logo Additions or Updates:
* [ ] My image is a `png` file.
* [ ] I uploaded my image to the `logos` directory.
* [ ] My image has a transparent background and is square (1:1 aspect ratio).
* [ ] My image is `512` pixels in width and height.
* [ ] My image's file name matches its mapping id.

### CODE REVIEW

**Comment by 128931** [comment]
skidders are haram this should be closed asap

**Comment by ziuee** [comment]
> skidders are haram this should be closed asap

then let’s close your mouth shall we? mr skid

**Comment by Scifi9902** [comment]
Wouldn't advise accepting the PR. The server being added is severely new and is not known by reputable people.

**Comment by ziuee** [comment]
> Wouldn't advise accepting the PR. The server being added is severely new and is not known or owned by reputable people.

This server was first launched in 2019, you’re sayin the server isn’t owned by reputable people even though you’re the one  people against me as you’re mad I exposed y’all for skidding code. Really sad that you go this far after a abusive manager was demoted from the server.

**Review by GrowlyX — APPROVED** [review]

**Review by GrowlyX — CHANGES_REQUESTED** [review]
Your server logo is not at least 512px in width/length.

**Comment by PrestigePvP** [comment]
Denied, for inappropriate community behavior. Please be more respectful to community members, if this happens again you will not be allowed to post or comment on this repo.

**Comment by ziuee** [comment]
> 

You’re denying my request as these idiots over here are attacking my ass for no reason. How does this make sense?

**Pull request closed without merging**
